#!/bin/bash

make clean
rm -rf `find . -name CMakeCache.txt` \
       `find . -name CMakeFiles` \
       `find . -name CTestTestfile.cmake` \
       `find . -name Makefile` \
       `find . -name cmake_install.cmake` \
       spim/parser_yacc.c \
       spim/parser_yacc.h \
       spim/parse_yacc.output \
       spim/scanner.c

